### ISSUE TITLE
No visibility in to pending batched jobs

### ISSUE THREAD

**Issue by JackWH** [laravel/horizon#1017]
- Horizon Version: 5.7.6
- Laravel Version: 8.39.0
- PHP Version: 8.1
- Redis Driver & Version: phpredis
- Database Driver & Version: N/A

### Description:

Horizon's "Pending Jobs" screen doesn't display any jobs which are pending as part of a batch. This can lead to situations where Horizon suggests there are no jobs being processed, when in fact, they're just hidden from the user.

We can determine whether there are pending batches by going to the Batches screen. However, batches which have been pending for a long time are nearly impossible to find, as they just get pushed down the list by completed batches. You might have to click the "Next Page" button countless times before you manage to hunt down a pending batch. I appreciate you can prune completed batches, but applications with high-frequency batches or low-frequency pruning requirements make this an unhelpful workaround.

Even once you've found a pending batch in the list, Horizon's UI only shows a count of the total jobs, a count of the pending jobs, and a count of the failed jobs. There's no way to determine exactly which job is next to be run, or gain any further insight in to the progress of the batch or its individual jobs.

### Steps To Reproduce:

Dispatch a batch of jobs to Horizon. Within one of the jobs, delay the batch. Try and find the delayed job within Horizon's UI, or find any info about which jobs are left to be processed — unless I'm missing something, you won't be able to.

I believe this is primarily a usability issue, but it may also be a bug.

**Comment by driesvints** [comment]
We don't yet support php 8.1, does it happen with a stable php version as well?

**Comment by JackWH** [comment]
Yes, I've been running PHP 8.1 locally, but 8.0 on production — same results on both.

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue and we'll re-open this issue.

**Comment by aryehraber** [comment]
We're experiencing this issue too. I thought I was causing the issue by clearing the app's cache or something, but that obviously shouldn't remove pending jobs.

I haven't nailed down _exactly_ when it happens, but basically we have batched jobs that take several days to process due to rate limiting, and after some time (more than a day I think), the jobs disappear from the Pending Jobs view but are still getting picked up by Horizon's workers (I can see them running in my terminal).

I'll try and recreate the issue using @driesvints's [above steps](https://github.com/laravel/horizon/issues/1017#issuecomment-836347520) but may take some time due to the long wait time.

**Comment by JackWH** [comment]
@aryehraber thanks, glad it's not just me! It sounds like our workflows are similar, though I had noticed batches disappearing after a few hours rather than days.

I had been meaning to respond to this but been super busy. Will try and put together a reproducible version myself shortly as well.

**Comment by aryehraber** [comment]
I've created a simplified version of our setup: long running job + slow rate limiter using middleware.

## Steps

1) Download Repo
https://github.com/aryehraber/horizon-issue-1017

2) Run Sail
`sail up -d`

3) Run command to dispatch large batch of jobs ([see here](https://github.com/aryehraber/horizon-issue-1017/blob/master/app/Console/Commands/DispatchLongRunningJobBatch.php)):
`sail artisan dispatch-jobs`

4) Run Horizon
`sail artisan horizon`

5) Wait for `X` hours/days (will edit once I see how long it takes on my end)

**Comment by aryehraber** [comment]
@JackWH Looks like you replied just before me 😅 

Feel free to pull down the above repo to see if this simplified case is similar to yours, and also run the test on your end if you have time (I'm just leaving it running in the background via Sail)

**Comment by aryehraber** [comment]
**Update** 

Looks like the Pending Jobs list cleared after just 1 hour (see screenshots below). 

@driesvints Let me know if you need any further info!

<img src="https://user-images.githubusercontent.com/5065331/118490488-476a9000-b71e-11eb-887b-56986e1df0a6.jpg" width="650">

<img src="https://user-images.githubusercontent.com/5065331/118490484-46d1f980-b71e-11eb-87cb-7cedfdc311ca.jpg" width="650">

<img src="https://user-images.githubusercontent.com/5065331/118490479-446f9f80-b71e-11eb-96ae-d20a8abc5084.jpg" width="650">

**Comment by aryehraber** [comment]
The fact that the list cleared at exactly an hour made me suspicious that this was by design... 😓

After some code diving I noticed this:
https://github.com/laravel/horizon/blob/a5d1c7450370dc99c6c9258b689cf7c539aef8b3/src/Repositories/RedisJobRepository.php#L84

I've definitely scrolled passed the "Job Trimming Times" config option a few times but always thought this was for `completed` & `failed` jobs, looking more closely I see `pending` in the list too. I'm not entirely sure why you'd ever want `pending` jobs to be trimmed but my guess is that increasing this value will "fix" the issue.

Would be great to get confirmation on this, and if possible the rationale behind trimming `pending` jobs?

**Comment by driesvints** [comment]
Ping @themsaid ^

**Comment by themsaid** [comment]
I can't replicate the issue. Dispatching jobs of a batch appears in the pending screen on Horizon. Need more details on how to replicate.

**Comment by driesvints** [comment]
@aryehraber @JackWH We're going to keep the default trimming of pending jobs at 1 hour. In our own experience jobs don't run that long. If you need this to be larger you're free to increase the value in your `horizon.php` file.

**Comment by aryehraber** [comment]
@themsaid @driesvints Thanks for looking into this! 

I believe what you suggest is what I realised after code-diving earlier: https://github.com/laravel/horizon/issues/1017#issuecomment-842306104

I can't really think of any reason why you'd want Pending Jobs to be trimmed from Horizon's UI while they continue to run hidden in the background, but either way I'll be increasing the value in `horizon.php` to account for our longer running jobs.

Thanks again!

**Comment by driesvints** [comment]
It's because in our experience jobs don't last that long (over an hour). Plus these defaults were sensible defaults that were added to prevent memory exhaustion errors when lots of jobs are processed.
