### ISSUE TITLE
Retrying failed jobs from Batches does not reset `cancelled` status

### ISSUE THREAD

**Issue by ThaDaVos** [laravel/horizon#1042]
- Horizon Version: v5.7.9
- Laravel Version: 8.50.0
- PHP Version: 7.4.z
- Redis Driver & Version: predis/phpredis: phpredis @ 5.3.4 (maybe add how to retrieve this?) https://github.com/phpredis/phpredis/issues/2
- Database Driver & Version: Mysql @ 5.7.25

### Description:
When retrying all failed jobs from the batch screen one would expect the batch to be uncancelled and if one is following the documentation to define a batchable job, the failed jobs would run: https://laravel.com/docs/8.x/queues#defining-batchable-jobs

BUT, as the batch isn't uncancelled and one started their `handle` method according to the documentation (see below code), yes they will succeed immediatly but not how one would expect as no part of the job has run...
```PHP
    /**
     * Execute the job.
     *
     * @return void
     */
    public function handle()
    {
        if ($this->batch()->cancelled()) {
            // Determine if the batch has been cancelled...

            return;
        }

        // Rest of job code
    }
```

### Steps To Reproduce:

Information given above see `Description`

**Comment by driesvints** [comment]
Heya, thanks for reporting.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue as separate commits on the main/master branch and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new bug-report --github="--public"
```

Please do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel to open up a new issue if you're still experiencing this.

**Comment by ThaDaVos** [comment]
Seriously... it's not even a week old... please give people sometime to do the stuff you asked or even respond... I've had a few really busy days since then...

**Comment by driesvints** [comment]
Feel free to open a new issue when you're ready 👍

**Comment by ThaDaVos** [comment]
Why would I open a new issue if it gets closed if I don't respond quick enough... don't see the point of reporting this anymore... 😒

Also I thought my description was clear enough as it was all according the docs...

**Comment by itabirca** [comment]
Steps to reproduce:
- create a batch with 1 job that fails intentionally
- use `Retry failed jobs` call to action
Expected: batch gets un-cancelled and failed jobs "run again" (as if the `Retry` call to action was clicked for each job)
Actual: all failed jobs get to "run again", but immediately complete because the batch is cancelled. 

This is so misleading.
