### ISSUE TITLE
Redis::pipeline(): Can't activate pipeline in multi mode!

### ISSUE THREAD

**Issue by srako** [laravel/horizon#1043]
- Horizon Version: 5.7.9
- Laravel Version: 8.51.0
- PHP Version: 7.3.29
- Redis Driver & Version: phpredis 5.2.2
- Database Driver & Version: redis 6.2.4

### Description:
``` php
Redis::pipeline(): Can't activate pipeline in multi mode! {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Redis::pipeline(): Can't activate pipeline in multi mode! at /www/vendor/laravel/framework/src/Illuminate/Redis/Connections/PhpRedisConnection.php:402)
[stacktrace]
#0 {main}
"} 
```

### Steps To Reproduce:

* repository :https://github.com/srako/horizon_bug

* When I run the following command, I will receive an error
```php
php artisan daily
```

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by henze-housepedia** [comment]
@srako, did you ever solve this? as a workaround I could use predis, but that is not really what I want...

**Comment by henze-housepedia** [comment]
I now use a workaround: basically what I did is override the PhpRedisConnection, the PhpRedisConnector, RedisManager and the RedisServiceProvider and use that provider instead of the original. Someone else already mentioned that if your change the pipeline method in PhpRedisConnection so it uses multi method instead of pipeline, everything runs fine, hope this helps anyone until someone finds a way to reproduce this, as this is what they need to fix the problem (they need to write tests for it).

Don't pass Redis::PIPELINE to the multi function, as it will give you the same problem.
