### ISSUE TITLE
Having no tries option in the supervisor causes unlimited tries

### ISSUE THREAD

**Issue by shivampawstickee** [laravel/horizon#1076]
- Horizon Version: 5.7.13
- Laravel Version: 8.49.2
- PHP Version: 7.4

### Description:
When there is no `tries` option set the `SupervisorOptions` class defaults `$maxTries` to 0 which causes an infinite loop when jobs fail.

Is this intended? My hunch is it isn't because in `Illuminate\Queue\WorkerOptions` the default is 1

I know that `tries` is set in the config file by default, but it still feels incorrect to me to have unlimited retries allowed?

Happy to create a PR if it is agreed this needs addressing.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by shivampawstickee** [comment]
I don't see how this isn't a bug? The current behaviour means leaving the `tries` field out of the supervisor config causes an infinite amount of attempts for a failed job.

**Comment by matheusb-comp** [comment]
@driesvints, I also think this is a bug.
In the Queue module of the framework, the default changed from 0 to 1 [since version 6.0](https://github.com/laravel/framework/pull/29385).

Also, in Horizon [since version 3.0](https://github.com/laravel/horizon/pull/704) the default `tries` in the config file was also changed to 1.
It just seems very strange to have a different default in Horizon **only** for this attribute.

**Comment by matheusb-comp** [comment]
> Having a better fallback?

I think just changing the [`$maxTries` default value](https://github.com/laravel/horizon/blob/2fc2ba769a592e92d170d85e346a5631b3a90ed5/src/SupervisorOptions.php#L206) from `0` to `1`, to match the `$maxTries` default value in [`Illuminate/Queue/WorkerOptions.php`](https://github.com/laravel/framework/blob/d9ee6cb059cf61d4e4f0a5f506eb57d48613f400/src/Illuminate/Queue/WorkerOptions.php#L68).

Since all the other default values are the same in both files, as @shivampawstickee said, it just does not seem intended to be `0`.

**Comment by driesvints** [comment]
If you could PR that (probably to master because it'll be a breaking change) with a thorough explanation for Taylor, he could have a look 👍
