### ISSUE TITLE
5.9.5 is causing an issue with the dashboard when compiling assets for production

### ISSUE THREAD

**Issue by dovid** [laravel/horizon#1140]
- Horizon Version: 5.9.5
- Laravel Version: 8.83.7
- PHP Version: 8.1.3
- Redis Driver & Version: predis/predis 1.1.10
- Database Driver & Version: MySql 8

### Description:

I have a feeling that the recent update to 5.9.5 is causing an issue with the dashboard when compiling assets for production (compiling for dev works fine). 

When going to the Horizon dashboard I got a blank screen. I see the HTML, but no ajax requests are made so the dash doesn't show any data.

I rolled back to 5.9.4 and it works just fine.

### Steps To Reproduce:

Compile production assets: `npm run prod`
Go to the Horizon dashboard page.

**Comment by driesvints** [comment]
Do you mean compiling your app assets or horizon's assets?

**Comment by oluomotoso** [comment]
I can confirm this same issue on Laravel 9. publishing horizon assets is showing a blank page
please check

**Comment by driesvints** [comment]
Pretty sure https://github.com/laravel/horizon/pull/1138 is the culprit. I'll revert that.

**Comment by Grldk** [comment]
@driesvints can we please debug this further before reverting? I've tested this quite thoroughly and didn't find any problems. And horizon not working with a strict CSP keeps being in issues for quite a few people.

@dovid do you by any chance have a custom horizon layout in your resources/views/vendor/horizon? Because of the changes in my PR that layout changes and the old layout can give a blank HTML.

**Comment by driesvints** [comment]
I released v5.9.6 that reverts the above PR. Does everything work for you all again?

**Comment by oluomotoso** [comment]
@driesvints yes it worked. tested on Laravel 9

**Comment by driesvints** [comment]
@Grldk gonna keep it reverted for now. We can't have people's Horizon setup's broken.

**Comment by Grldk** [comment]
@driesvints I get that, and appreciate it. Otoh: reverting this breaks Horizon for people like me with a strict CSP. And I'd really like to fix this, which is harder when just reverting without any chance of debugging.

**Comment by driesvints** [comment]
> Otoh: reverting this breaks Horizon for people like me with a strict CSP.

I don't see a big issue here. I've never know much people to have a problem here. I think we should consider the majority of the Horizon users here rather than a few people who want a strict CSP. If there is a certain solution for your use case that 100% won't break people's setups we can maybe reconsider it.

**Comment by oluomotoso** [comment]
> @Grldk I'd like to get more info on what went wrong this time.
> 
> @dovid or @oluomotoso ... do you have a custom Horizon layout in resources/views/vendor/horizon?

I don't. The only information worth stating is that I just recently upgraded to Laravel 9.

**Comment by shopisaur** [comment]
I too can confirm blank page & no ajax requests with horizon version 5.9.6
I also have no custom layout in resources/views/vendor/horizon.

This happened for me only after updating to 5.9.6 & running php artisan horizon:publish

**Comment by Grldk** [comment]
@taylorotwell thanks. This time around I'm puzzled why it's not working in some setups. As I said, I tested this quite thoroughly, and the only problem I ran into was with an outdated (by my PR) layout in the views/vendor dir.. So I haven't got a clue why this isn't working for some people.
