### ISSUE TITLE
Since 2.4 - addSecon() is deprecated. Use addSeconds() instead.

### ISSUE THREAD

**Issue by ukhflf** [laravel/horizon#1321]
### Horizon Version

4.3

### Laravel Version

7.29

### PHP Version

7.4.3

### Redis Driver

PhpRedis

### Redis Version

5.0.0

### Description

when we start horizon the command response us 

Since 2.4 - addSecon() is deprecated. Use addSeconds() instead. ["exception"."object) (ErrorException(code: 0): Since 2.4 - addSecond() is deprecated. Use addSeconds()instead. at /data/to/your/project/vendor/cakephp/chronos/src/Traits/ModifierTrait.php:863)

and horizon shutdown

### Steps To Reproduce

when we start horizon the command response us 

Since 2.4 - addSecon() is deprecated. Use addSeconds() instead. ["exception"."object) (ErrorException(code: 0): Since 2.4 - addSecond() is deprecated. Use addSeconds()instead. at /data/to/your/project/vendor/cakephp/chronos/src/Traits/ModifierTrait.php:863)

and horizon shutdown

**Comment by crynobone** [comment]
Hey there,

Unfortunately we don't support this version of the library anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!

**Comment by ukhflf** [comment]
Thanks! brother.

**Comment by brandonbronisz** [comment]
@ukhflf This is due to a conflict in `cakephp/chronos` and version >=2.4. 

I came across this as well while going through the rounds of upgrading laravel from 6.x to 7.x. 

this is by no means a permanent fix but if you can't get to upgrading to laravel 8.x and horizon 5.x yet this is a working **temporary** fix: 

Append the following to your composer.json file
```
    "conflict": {
        "cakephp/chronos": ">=2.4.0"
    },
```

this will lock the dependency to 2.3.x. I've tested this and works as a solution until you can get to 8.x
