### ISSUE TITLE
i get error with predis v 2.2.2

### ISSUE THREAD

**Issue by Rasoul-Karimi** [laravel/horizon#1459]
### Horizon Version

5.24.5

### Laravel Version

11

### PHP Version

8.2

### Redis Driver

Predis

### Redis Version

2.2.2

### Database Driver & Version

postgresql 15

### Description

hi
i get eror with predis v 2.2.2 every secound:

`vendor/composer/../predis/predis/src/Command/ZSetRemove.php): Failed to open stream: No such file or directory vendor/composer/ClassLoader.php:571)`

i donwgrade predis to v1.1.10 no get this error every secound

`vendor/composer/../predis/predis/src/Command/Redis/ZREM.php)`

### Steps To Reproduce

laravel new bug-report --github="--public"

**Comment by crynobone** [comment]
Hey there, thanks for reporting this issue.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue *as one separate commit* on the main/master branch and share the repository here?

Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com/) properly set up.

    laravel new bug-report --github="--public"

Do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel to open up a new issue if you're still experiencing this.
