### ISSUE TITLE
Retry job creates new failed job on failure 

### ISSUE THREAD

**Issue by rich-bede** [laravel/horizon#310]
In the event of a failed job retry Horizon creates another failed job resulting in multiple failed jobs. Is this the designed behaviour? Repeated retry failures (e.g. job makes API request, API server is down) will result in many "duplicate" jobs being created when potentially you'd only want to retry the original failed job. If all duplicates were evicted when one had succeeded then this issue could be worked around but currently I'm stuck with the duplicates in the UI as given the nature of my job's handler only one would ever succeed, the rest would continue to fail (and spawn more failed jobs).

**Comment by MovingGifts** [comment]
I agree, it looks like something is wrong with how `failed_jobs` work. When looking at the `failed_jobs` table, you'll see that the original failed job is there, EVEN after retrying it in the UI and it succeeds. This leaves the failed job row in the db, which I believe is incorrect behavior, since the retry succeeded, so the original failed job should be removed from the `failed_jobs` table as well.

Shouldn't this be default behavior? Any thoughts on this or how to accomplish this?

**Comment by rich-bede** [comment]
After more digging through the source code: 

With regards to the "duplicates" following multiple of the same failed jobs, these occur due to the fact that retrying a failed job is the same as dispatching a new one, as far as laravel/horizon is concerned it is a new job. So this looks to be as designed but still is problematic as described above.

**Comment by MovingGifts** [comment]
I hope someone else can chime in, as this is a pretty important bug that can **easily lead to duplicate jobs**. I think when retrying a failed job in horizon:
- It should retry the _same_ job with the _same_ job id, not create a new job (since there is no way of knowing the original job succeeded when it is still in the `failed_jobs` table)
- An alternative with the current new job creation and processing it as a failed job, would be if we retry a failed job and it succeeds, horizon should have an internal reference to the original job id that failed, so that the original failed job can be removed from the `failed_jobs` table

**Comment by Donny5300** [comment]
Does that happen when you restart your Horizon instance? When i restarted the instance, my code was executed correctly at the second time.

**Comment by driesvints** [comment]
This is by design. When a job has failed and is retried it's considered to be a new job.

**Comment by dimer47** [comment]
@driesvints Can we propose a PR to give developers the choice to either stick with the default behavior set by Laravel Horizon, which is to create a new task and keep the old one, or to choose to retry a job with the same UUID and delete the retried job? Are the maintainers open to this suggestion, or is it a categorical no? If it's a definitive no, please specify this in the official documentation to avoid multiple issues and questions on the support channels that you seem to frequently suggest.

We hope you understand our perspective and will provide us with a response other than directing us to discussion channels.
