### ISSUE TITLE
Jobs seems to be picked up by multiple worker

### ISSUE THREAD

**Issue by azrulamir** [laravel/horizon#315]
I am running horizon on horizontal scale setup with multiple server running a same instance. I found that once in a while there are jobs that's being processed multiple times and somehow passed my constraint checking. 

I suspect this could be cause by that job being processed by multiple workers at the same time, hence it manage to pass the constraint check I have on the job handle() function.

So my question, is horizon are fully compatible to run on horizontal scaling setup?

**Comment by halaei** [comment]
As far as I know, it is impossible for a job being picked by 2 workers at the same time.
There could be a chance that a jobs takes longer than `config('queue.redis.retry_after')` seconds and get retried by another worker.

> So my question, is horizon are fully compatible to run on horizontal scaling setup?

I don't know, but can you describe what is your setup? Does each instance have it's own redis server? If yes, how are they connected to each other?

**Comment by azrulamir** [comment]
> There could be a chance that a job takes longer than config('queue.connections.redis.retry_after') seconds and get retried by another worker.
From the recent jobs section in horizon dashboard, it doesn't show any jobs that took longer times to process, all of them are running below 1 second runtime. But after viewing this issue here #158, i increased the retry_after settings to 900 but still the issue is there.

> I don't know, but can you describe what is your setup? Does each instance have it's own redis server? If yes, how are they connected to each other?
Each instance are connecting to a central/single redis-server instance. I can see from Horizon dashboard that it can detect all of the running instance.

My application is a simple voting api system that collects vote requests from client and process it via laravel queue horizon. Each job requests has a validation logic inside the handle() function but with the duplicates happening, it somehow doing one  single request multiple time simultaneously. Appreciate your help.

**Comment by Donny5300** [comment]
Did you set the settings correctly? You can choose at: 
```
return 'environments' => [
            'local' => [
                'supervisor-1' => [
                    'connection' => 'redis',
                    'queue'      => [ 'default' ],
                    'balance'    => false,
                    'processes'  => 3,
                    'tries'      => 3,
                ],
            ],
        ],
```

https://laravel.com/docs/5.6/horizon

See the section `Configuration`

**Comment by halaei** [comment]
So you have multiple php servers connecting to a single redis server. Here are 2 causes that come into my mind:
1. The servers must be synced in time, e.g via NTP. Otherwise, jobs reserved by one server might be considered expired by another.
2. If servers are synced, there could be a chance that you are detecting duplicates due to a reason other than jobs being picked up by multiple workers. For example, maybe your database transactions are not in the correct isolation level and you push duplicate jobs into the queue.

Other than that, it seems to me than picking a job twice is impossible.

**Comment by emielmolenaar** [comment]
Are you sure you are not dispatching the job multiple times, for example by events or observers?

**Comment by andreladocruz** [comment]
Why don't setup the retry_after in horizon.php configuration file?

This is my configuration today:

`'production' => [
            'default' => [
                'connection' => 'redis',
                'queue' => ['default'],
                'balance' => 'simple',
                'processes' => 1,
                'tries' => 3,
            ],
            'marketplace' => [
                'connection' => 'redis',
                'queue' => ['marketplace'],
                'balance' => 'simple',
                'processes' => 1,
                'tries' => 3,
            ],
            'autoresponder' => [
                'connection' => 'redis',
                'queue' => ['autoresponder'],
                'balance' => 'simple',
                'processes' => 1,
                'tries' => 3,
            ],
            'clicks' => [
                'connection' => 'redis',
                'queue' => ['clicks'],
                'balance' => 'simple',
                'processes' => 2,
                'tries' => 3,
            ],
        ],` 

The retry_after should be configurable by queue, right?

**Comment by driesvints** [comment]
As explained by others above the problem is probably using the same redis queue on multiple apps. It should be impossible for Horizon to process the same job twice. If you still believe this to be a problem please provide more details and preferable the configuration of your app(s).

**Comment by dpde** [comment]
What about having multiple worker servers that process the same queue?
I guess I observed that jobs have been proccessed multiple times.

My setup:
1 webserver, 1 redis server, 3 Worker servers that process the same queue.

**Comment by sergiq** [comment]
Maybe this is closed but since I have horizon, time to time job is processed by the same job at the same time. Also I know that a screenshot it's not an evidence but I can reproduce it (only appear time to time)
![image](https://user-images.githubusercontent.com/1035477/55493350-12cc1500-5639-11e9-9da0-b8e2574a4d93.png)

I have 2 backends with 1 worker each listening the same queue

**Comment by halaei** [comment]
@dpde @sergiq Are the followings helpful:

1. Make sure different applications that are supposed to be isolated doesn't share the same redis database.
2. There is a chance that a job takes longer than config('queue.connections.redis.retry_after') seconds and get retried by another worker.
3. [If you have multiple physical servers] The servers must be synced in time, e.g via NTP. Otherwise, jobs reserved by one server might be considered expired by another.
4. There is a chance that you are detecting duplicates due to a reason other than jobs being picked up by multiple workers. For example, maybe you push duplicate jobs into the queue, maybe because your database transactions are not in the correct isolation level.
5. Horizon and Laravel Redis queue driver doesn't support Redis clustering.

**Comment by sergiq** [comment]
thanks @halaei for your answer, but:

1. there is only one database with one app
2. the job is processed at the same time (i had both timestamps when the job starts and both are the same second)
3. both servers has NTP ofc
4. No, the job event only throw one log (one job)
5. Yes, i know it.

Also never happened with the normal laravel workers (maybe in more than 1 year).

**Comment by halaei** [comment]
@sergiq Can you explain your screenshot? What are the rows and columns and how does it show jobs are picked twice?

**Comment by sergiq** [comment]
The screenshot is small part of a job information (uuid). this picture shows when the job is executed (the first field is just an auto increment and the last one is who performs the action).

**Comment by halaei** [comment]
Horizon redis queue driver is just a wrapper for laravle redis queue driver that actually doesn't touch queues but fire some events for monitoring. It also changes the job IDs to incrementing integers. I don't see how possibly these changes can cause jobs being handled twice. To me the screenshot doesn't reject 2 jobs being simultaneously handled by 2 workers. It would be a lot helpful if you could provide more information.

**Comment by sergiq** [comment]
Hi @halaei thanks for your response :) As I mentioned, a team gonna set up the same environment in dev as we have in production and try to detect when and why. I changed this morning the workers in production to use the laravel's one and everything is working ok (but it's to early to assume it). Let's see if have the same behavior that have in the last year with 0 duplicateds

**Comment by trip-somers** [comment]
This is almost definitely happening to me but only on my Homestead instance and not on my production server. I'm going to try updating Homestead, since it's only happening there.

For anyone interested, here's my list of symptoms:
* Job A contains a `if (! Storage::exists($folder) && ! Storage::makeDirectory($folder))` line that results in a "mkdir(): File exists" error. That's a hell of a race condition even if two jobs are being processed at the same time, but I get it about 10 times every night while overnight jobs are processing.
* Job B contains an insert-or-update statement that throws exceptions nightly for inability to insert due to collision with unique rule (which is why the insert-or-update statement exists in the first place).

I know this isn't the best way to "prove" that two workers are picking up the same job at the same time, but there's not a lot else that makes any kind of sense.

As stated above, this is only happening on my Homestead, and it only started about 2 weeks ago after I upgraded from Laravel 5.6 to Laravel 5.8 (and Horizon from 2.x to 3.2.x). My Homestead and production servers are both running off the same composer lock file with Laravel 5.8.18 and Horizon 3.2.1. My Homestead is a little older, so I am going to attempt to upgrade that.

**Comment by trip-somers** [comment]
Updating Homestead seems to have corrected the issue for me, whatever it was.

**Comment by bkuhl** [comment]
I'm also seeing this issue on my production environment.  The queue jobs have additional checks in place to ensure the job isn't processed more than once, but because 2 workers have picked up the same job at the same time, the database record to ensure the job doesn't get processed twice isn't obeyed because it hasn't yet been written by either job.  This isn't a new issue and has been happening for a long time.  

Horizon v5.7.3

Here's some of my queue config:

```php

                'balance'       => 'auto',
                'processes'     => 7,
                'tries'         => 0, // indefinitely

                // 5 seconds under the queue's retry_after to avoid overlap
                'timeout'       => (Carbon::SECONDS_PER_MINUTE * 10) - 10, // Just under 10 mins
```

**Comment by graemlourens** [comment]
@bkuhl We run 300 jobs / second on our stack and have never had this issue. 
It highly depends on how you have setup retry_after, timeout etc on your jobs.

What is your retry_after setting on the queue connection to redis? this HAS to be slighly longer than the longest running job on the queue and has to be also slighly longer than the timeout that is set.

**Comment by bkuhl** [comment]
Our queues operate in bursts and may be loaded with 500k jobs with 11 concurrent workers.  We only experience this issue when the queue gets initially loaded with jobs.  Once there's plenty of jobs on the queue it doesn't happen.  Average execution time on the jobs being duplicated is 2-3 seconds.

**Comment by graemlourens** [comment]
@bkuhl how sure are you that you're not by mistake actually indeed dispatching certain jobs multiple times? are the job id's actually the same or different?

**Comment by bkuhl** [comment]
That's a good question, and one that I should have investigated more before posting here.  I'll have to do some digging on that and get back to you, I'm only assuming that's the case.

**Comment by graemlourens** [comment]
@bkuhl sure, get back if you have any 'hard evidence' (which sometimes is extremely hard to obtain!). Happy to help. We do a lot of logging, for example you can register a callback with Queue::before() and log the ID oft he job somewhere in order to see if actually this is the case that workers are picking up the same job with the same id (which i doubt to be honest).

**Comment by bkuhl** [comment]
I can confirm that some "duplicate jobs" on my end have unique `ID` for each job, suggesting it's not the workers picking up duplicates, but an issue on the pushing side.

**Comment by trip-somers** [comment]
If you figure out what's causing the extra pushes, please come back and let us (at least me) know what it was. I've never been able to figure it out, but I would suspect is has something to do with the communication between Laravel and Redis.

Has anyone in this thread experienced this with a different queue provider?

**Comment by graemlourens** [comment]
@bkuhl we're one step further! :) I'd also be interested to hear if and when you figure out what is causing it. We have never experienced this and have bulk-pushed up to 500'000 jobs sometimes in one go (parallel), which never led to duplication that we know of.

**Comment by bkuhl** [comment]
I've added logging in my application both where jobs are pushed to the queue and where jobs are processed.  I can confirm that only 1 job is being pushed to the queue, but multiples are being picked up.

I have 30 processes processing this queue that sends messages to Discord channels.  My system pushes a job to the queue for each message/channel combination.  I added logging when each job is queued and when the job is processed by a worker.  According to those logs, I'm seeing that only 1 job was queued (I'm using [Laravel's batch `add()`](https://laravel.com/docs/8.x/queues#adding-jobs-to-batches) to bulk add jobs to the batch), but 3 jobs were picked up with unique `uuid`'s on 3 different workers.

**I'm not sure what steps I should take for next steps to troubleshoot the issue further.  Any suggestions?**  I just updated Horizon last night, so I'm using `v5.7.5` with `redis:6.0-alpine` and have also upgraded to `redis:6.2-alpine` and see the issue there as well.  I'm able to reproduce this issue with my local environment as well.

**Comment by bkuhl** [comment]
I added a `var_dump($jobs->all());` to [this line](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Bus/Batch.php#L189) and confirmed that only 1 job is being pushed to the queue locally.

**Comment by bkuhl** [comment]
I'm going to remove my other comments to keep this thread clean, but I've confirmed it was a logic issue on my end :-\

**Comment by trip-somers** [comment]
@bkuhl After reading your now-deleted comment yesterday, I gotta know what the logic issue was, lol

**Comment by bkuhl** [comment]
Haha, With Laravel 8 I had upgraded to use batches for these jobs, and I was supplying some jobs when the batch was created, but also re-adding those same jobs via `$batch->add()` _in certain conditions_, leading to a handful of jobs being added twice.  Definitely a 🤦 moment, but entirely my fault.

**Comment by trip-somers** [comment]
Dangit. You were my big hope for finally diagnosing why this happens to some people. Thanks for explaining.

**Comment by bkuhl** [comment]
Ah, sorry. I'm still monitoring things for the next few days so maybe something will come to light.  This may help folks...

I noticed the UUIDs on my jobs were unique.  At first I thought it was retries, but noticed all `attempts` were `1`, so I was able to rule that out.  Secondly, I wondered where the UUIDs were coming from, so I ended up adding logging to where the UUID was generated [here](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Queue/Queue.php#L141).  This enabled me to confirm that multiple jobs were indeed being fired by my app's logic.  To figure out when/how I modified this code to conditionally throw exceptions to expose the stack trace (could also use xdebug or more extensive logging) enabling me to see what was causing the events.

**Comment by adddz** [comment]
Is this issue still happening? I'm about to move my setup to a multiserver setup with multiple worker servers.
Once I run Horizon all the worker servers, how will I be able to access the `/horizon` UI web page from the app servers are behind a load balancer? The worker servers don't have any access to HTTP, they just run jobs.

**Comment by bkuhl** [comment]
No, I mentioned in my last comment this was an issue in my app's logic.

**Comment by adddz** [comment]
> No, I mentioned in my last comment this was an issue in my app's logic.

Yes I’ve read that. But how are you able to access the Horizon URL when Horizon is running only on the worker servers?

**Comment by bkuhl** [comment]
I'm happy to help, but this discussion is completely off-topic for this thread so you should post on StackOverflow.  I'll delete previous comments related to this topic.
