### ISSUE TITLE
Customizable Laravel Horizon dashboard route

### ISSUE THREAD

**Issue by jofomah** [laravel/horizon#365]
I would like to link Laravel Horizon route `/routes` to my admin navigation  bar and also my app admin `logout` and `home` route to `/horizon` navbar so that i can easily navigate from Horizon dashboard to my admin dashboard and also logout from Horizon dashboard.

I.e is there a way to add a custom route to Horizon navbar so that it is easy to link it to ones app routes???

**Comment by driesvints** [comment]
Horizon is a SPA which means everything is rendered client side. Since everything is compiled I don't see how we could offer a way through the package to make this happen.

What you *could* theoretically do is overwrite the base view and build some styling/html around it. Add a file to this location: `resources/views/vendor/laravel/horizon/app.blade.php` with the contents of https://github.com/laravel/horizon/blob/3218e86cea737643fa626fc98d56a3b846f8ba2a/resources/views/app.blade.php and you could build around it as long as you allow the SPA to generate everything to the root div.

**Comment by abdosaeedelhassan** [comment]
may be switching to build every pages using livewire components solve the problem
