### ISSUE TITLE
Exception when using horizon with laravel 5.7

### ISSUE THREAD

**Issue by mathiasmoser** [laravel/horizon#384]
Exception "The "stop-when-empty" option does not exist." when processing messages

https://github.com/laravel/horizon/blob/513fc37e6db7e0bf9eb0721a3a9fdcc0c43ee0c0/src/Console/WorkCommand.php#L14

it seems that the option stop-when-empty is missing in Horizon Work Command

**Comment by jasrys** [comment]
Same issue here when upgrading to 5.7.2. ![image](https://user-images.githubusercontent.com/11322354/45179224-c452b700-b1cc-11e8-995d-9d087d36d142.png)

@mathiasmoser, I reverted back to version 5.7.1 of the framework by explicitly requiring 5.7.1 instead of 5.7.* in my `composer.json` file, restarted horizon and my queues are processing normally again.

**Comment by DarkaOnLine** [comment]
Same here. It looks like this is related to this PR: https://github.com/laravel/framework/pull/25116

**Comment by bbashy** [comment]
Same here. 5.7.2 has some bug fixes in as well that are needed.

**Comment by DarkaOnLine** [comment]
We have a PR for a fix: https://github.com/laravel/horizon/pull/385

**Comment by bbashy** [comment]
Merged! Waiting on a release I think? Thanks @themsaid

**Comment by santigarcor** [comment]
Any news on this? I saw that @themsaid reverted that PR.

**Comment by driesvints** [comment]
Should be fixed now.
