### ISSUE TITLE
Optimize the amount of data loaded on "failed jobs"

### ISSUE THREAD

**Issue by BoyeMagnus** [laravel/horizon#398]
**Problem:**
When you're on the "failed jobs" tab, horizon hits the server every 3 seconds to check for updates. This becomes a problem because a lot of unused data is transferred. The ajax requests load a lot of information such as the exceptions and commands that is not being displayed. 
One of these requests (with 20 failed jobs) contains about 200kb of data. If you forgot to close the tab for about 10 minutes the amout of data transferred becomes about 40mb (200kb * (60s / 3s) * 10m).

**Solution:**
Only load "Job | On | Tags | Runtime | Failed At | Retry".

**Comment by driesvints** [comment]
Heya, thanks for sending this in. Since I haven't found any other issue about this particularly thing I'm going to close this. If more people would agree that this is an issue we could look into adding an option to set the refresh interval. But for now I think this doesn't warrant any changes. Hope you understand.

**Comment by driesvints** [comment]
Heya. turns out someone else also asked for this. See https://github.com/laravel/horizon/issues/327
