### ISSUE TITLE
Restaring horizon via horizon:terminate & suprevisord can cause long delay on jobs 

### ISSUE THREAD

**Issue by halaei** [laravel/horizon#400]
Currently, I issue a `artisan horizon:terminate` and wait for supervisord to start horizon after the current horizon process gets terminated.
This approach has an issue. If there is a job that is supposed to take 1 hour more to gets processed, horizon:terminate will wait for that job one hour without processing other jobs. So it forces a 1 hour delay.

PS: Another option is to call `artisan queue:restart`. However, this command has some limitation. One is that restarted jobs don't receive changes in the .env file. Another issue is it doesn't let the horizon know of any change in it's own configuration.

**Comment by halaei** [comment]
I think the main reason for this "bug" is because parent processes sleep for their children to get terminated. I think it is because if we don't place sleep we are going to have orphan workers. More specifically what happens is:
1. Master supervisor sends a signal to sub-supervisors to terminate.
2. Each sub-supervisor receives the signal and propagates it to their children to terminate. However, the master supervisor can gets terminated before the sub-supervisor deliver the signals to children. Now because the master supervisor is terminated, the sub-supervisor can also gets terminated due to either a failed attempt to echo something in STDOUT or receive of a SIGHUP - I am not sure which but I guess STDOUT closure is more likely to be the reason.
3. The children that never received any signal and never echo anything in terminal will continue fetching jobs and never terminate.

**Comment by halaei** [comment]
see http://php.net/manual/en/function.ignore-user-abort.php

**Comment by mfn** [comment]
> This approach has an issue. If there is a job that is supposed to take 1 hour more to gets processed, horizon:terminate will wait for that job one hour without processing other jobs. So it forces a 1 hour delay.

> I think the main reason for this "bug" is because parent processes sleep for their children to get terminated. 

Hmm, are you really really sure about this?

Isn't it rather different, especially when using supervisor? Because in my experience you can't tell supervisor to have such a long timeout and thus it will forcefully terminate the horizon maser processs

 Have you ever experienced something like this?

>     1. To remove the codes that waits for children to be terminated.

I too don't see the point of waiting for "worker" (if this is what's meant here?) because they could run a job.

By my expectations: I would **not** want to stop a worker processing a job when horizon receives a signal to terminate.

The worker should finish processing and _then_ exit.

Terminating the master is in 99% the case for simple reloading because the code base changed. This doesn't help a running job anyway.

The other 1% is a scheduled maintenance when you *really* need to make sure all workers are stopped (because you're taking down your database for an upgrade, etc.)

In this case we would need something different. You either wait until all worker are done or manually kill the ones _still running_.

It's important for this that a worker will be able to terminate on its own in this case:
- job is done
- it's supervisor does not exist anymore (i.e. the supervisor signaled the worker to terminate, but the worker was in the middle of processing a job)

**Comment by halaei** [comment]
> Hmm, are you really really sure about this?

Yes, I created a test and see it can happen. By default horizon:terminate can take no longer than 60 seconds, which on its own is also too much for me. But if you increase timeout config in horizon, you may increase that as well.

```
    'environments' => [
        'production' => [
            'supervisor-1' => [
                'connection' => 'redis',
                'queue' => ['default'],
                'balance' => 'simple',
                'processes' => 10,
                'tries' => 3,
                'timeout' => 3600,   ///////////// Here 
            ],
        ],
```

I think it is totally possible for a supervisor to let their workers know they should complete their current job and then terminate without actually waiting for the workers at all. So what I mean is that supervisors can call exit() and terminate themselves without forcing their children to immediately quick, and without allowing them to continue processing more jobs from the queues.

**Comment by mfn** [comment]
> By default horizon:terminate can take no longer than 60 seconds, which on its own is also too much for me. But if you increase timeout config in horizon, you may increase that as well.

But not only this, when using supervisor you also have to set `stopwaitsecs` accordingly (see The number of seconds to wait for the OS to return a SIGCHLD to supervisord after the program has been sent a stopsignal. If this number of seconds elapses before supervisord receives a SIGCHLD from the process, supervisord will attempt to kill it with a final SIGKILL. ):
> The number of seconds to wait for the OS to return a SIGCHLD to supervisord after the program has been sent a stopsignal. If this number of seconds elapses before supervisord receives a SIGCHLD from the process, supervisord will attempt to kill it with a final SIGKILL.

But
> So what I mean is that supervisors can call exit() and terminate themselves without forcing their children to immediately quick, and without allowing them to continue processing more jobs from the queues.

Yes, we're on the same page here. That would be my requirement too.

**Comment by halaei** [comment]
A lot of things mean supervisor hear (horizon has 2 type of supervisor, then we have supervisord as well). No wonder why everything is confusing :).

@mfn I think what you mention about `stopwaitsecs` is about supervisord and when you restart a process that is monitored by supervisord, probably using supervisorctl. I usually don't use that, because as you say, it may kill the process with SIGKILL.

Anyway, I am working on it, my PR is almost ready.
