### ISSUE TITLE
Failed job logs original Exception in lumen.log, but it's only listed as failed after six minutes

### ISSUE THREAD

**Issue by jfoliveira** [laravel/horizon#437]
Hi,

I noticed a weird pattern in my failed jobs and I hope you guys might be able to shed some light on it.
My questions at the end of this description.

## Timeline:

1. **[2018-11-07 16:24:06]**: Job has been started

2. **[2018-11-07 16:24:07]**: A second later an exception is logged in `storage/logs/lumen.log` - which is the original cause of my job to be failing:
```[2018-11-07 16:24:07] production.ERROR: Symfony\Component\Debug\Exception\FatalErrorException: Method Illuminate\View\View::__toString() must not throw an exception, caught ErrorException: Undefined variable: myVar (View: /home/app.com/resources/views/email/email.blade.php) in /home/app.com/app/MyClass.php:0```

3. **[2018-11-07 16:30:07]**: Only 6 minutes (six minutes), 360 seconds later, the job fails on Horizon:
* ### Exception displayed in Horizon:
```Illuminate\Queue\MaxAttemptsExceededException: EmailNotificationJob has been attempted too many times or run too long. The job may have previously timed out. in /home/app.com/vendor/illuminate/queue/Worker.php:400```

* ### Exception logged in `lumen.log` at the very same timestamp:
```[2018-11-07 16:30:07] production.ERROR: ErrorException: Undefined index: driver in /home/app.com/vendor/illuminate/database/DatabaseManager.php:115```

4. After fixing the error `Undefined variable: myVar`, everything works as expected.

## Questions:

1. As I noticed dozens of jobs following the same pattern of waiting six minutes until they listed as failed in Horizon, could you point me to any setting that I could be missing here and might be instructing horizon to wait for 6 minutes?

Below the relevant parts of my current configuration files:
### config/queue.php:
```
        'redis' => [
            'driver' => 'redis',
            'connection' => env('QUEUE_REDIS_CONNECTION', 'default'),
            'queue' => 'default',
            'retry_after' => 120,
        ],
```

### config/horizon.php:
```
    'environments' => [
        'production' => [
            'supervisor-1' => [
                'connection' => 'redis',
                'queue'      => ['sms', 'email', 'default'],
                'balance'    => 'auto',
                'processes'  => 10,
                'tries'      => 3,
                'timeout'    => 90,
            ],
        ]
```

2. Why isn't the original Exception displayed/logged with the failed job in Horizon? Any settings that I am missing?
That would have saved developers some time on figuring out the original issue.

**Comment by driesvints** [comment]
I'm not really sure if this is an issue or rather normal behavior. My best guess is that is that because your job is tried 3 times with a timeout of 90 seconds (total of 270 seconds) and then some remaining time before it actually gets logged.

Can you first please try one of the following support channels? If you can actually identify this as a bug, feel free to report back.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
