### ISSUE TITLE
I dont want to retry job

### ISSUE THREAD

**Issue by xyrintech** [laravel/horizon#567]
First of all, thank you so much for creating this package. 
I am have been trying to figure an option with this package and realised that  there is nothing no retry option available in this package. 

Lets say if we need to fail a job and simply do no want "retry" then there need to have an option for this. Such situation are important when we need to have something from third party server.

**Comment by browner12** [comment]
Are you proposing removing the "Retry" button from the failed jobs list? Some people definitely use that, so I don't think we can remove it.

You can define a `$tries` property on your job and set it to 1, so it is only tried once.

**Comment by xyrintech** [comment]
I agree retry button is very important.
Setting the `$tries = 1;` solve but at the same time its very confusion to understand the log. Lemme give you an example. I created a job as below and my `$retry_after` is set to 60 in queue.php. Now, ideally job failed immediately after 1 second due to timeout but at the same it waits for another 60 seconds to to call failed function (I believe its due to retry_after). Ideally if the job `$tries` set to 1 then why to wait for retry to call failed function. Hope this helps to identify the issue.

I have tried this at my end:
```
<?php

namespace App\Jobs;

use Illuminate\Bus\Queueable;
use Illuminate\Queue\SerializesModels;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;

class FetchAmazonOrders implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;
    
    public $timeout = 1;
    public $tries = 1;

    /**
     * Create a new job instance.
     *
     * @return void
     */
    public function __construct(int $website_id, $mode)
    {
        
    }

    /**
     * Execute the job.
     *
     * @return void
     */
    public function handle()
    {
        \Log::info("before sleep");
        sleep(2);
        \Log::info("after sleep");
    }
    
    public function failed($exception = null)
    {
        \Log::info("fail");
    }
}

```

Horizon log:
```
[2019-04-05 09:45:31][1961] Processing: App\Jobs\FetchAmazonOrders
before sleep
[2019-04-05 09:46:33][1961] Processing: App\Jobs\FetchAmazonOrders
failed
[2019-04-05 09:46:33][1961] Failed:     App\Jobs\FetchAmazonOrders
```

**Comment by browner12** [comment]
Have you identified an actual bug in Horizon? To me this sounds like a userland issue, and I would suggest moving this question over to StackOverflow, unless you can dig into the code and find something.

**Comment by xyrintech** [comment]
Actually its a bug, this the actual Horizon log.
Earlier I thought that this a figure but after reviewing your comments I figured out that this is a bug. 

Think of like this:
`$retry_after = 60` (presumption)
If a job needs to be executed once i.e. `$tries = 1 `and say it takes 5 seconds to execute but during its execution it fails. Now you would expect the `failed()` function to be called immediately when the job fails. But currently it waits for another 60 seconds to call fail function. 

Ideally there is a need to check if the `$tries = 1` and job fails then execute the `failed()` function. If the `$tries > 1` then we need to give it a retry based on `$retry_after` execution time.

I have replicated the same logic for you in my previous comment above with the log.

**Comment by djtarazona** [comment]
I think I understand what @xyrintech is saying. I may be wrong, but my understanding is that if a job exceeds the timeout, the worker processing that job will be killed **without marking the job as failed** even if the job has reached its maximum number of attempts. Since the worker is [abruptly](https://github.com/laravel/framework/blob/abefa7b2f3101f8070c79f67d3d7e0944d5ef173/src/Illuminate/Queue/Worker.php#L143) [killed](https://github.com/laravel/framework/blob/abefa7b2f3101f8070c79f67d3d7e0944d5ef173/src/Illuminate/Queue/Worker.php#L570), the `retry_after` time must elapse before another worker attempts to retry the job. At this time, the worker [checks the number of attempts](https://github.com/laravel/framework/blob/abefa7b2f3101f8070c79f67d3d7e0944d5ef173/src/Illuminate/Queue/Worker.php#L320) before running the job, determines the job has already been attempted the maximum number of tries, and finally marks the job as failed.

So if you have a `timeout` of 5 seconds, but a `retry_after` of 60 seconds. A job that hits the timeout limit will not be marked as failed until after at least 60 seconds, because the check for exceeding the number of attempts doesn't happen until the job is dequeued again after having been put back on the queue due to the 60 seconds `retry_after` elapsing (job never completed because it timed out).

It would be nice if the worker marked the job as failed before [killing itself / exiting](https://github.com/laravel/framework/blob/abefa7b2f3101f8070c79f67d3d7e0944d5ef173/src/Illuminate/Queue/Worker.php#L143) if it determines the job has already reached its max number of attempts, similar to what the worker does if an [exception is thrown](https://github.com/laravel/framework/blob/abefa7b2f3101f8070c79f67d3d7e0944d5ef173/src/Illuminate/Queue/Worker.php#L357). Something like this:

```php
protected function registerTimeoutHandler($job, WorkerOptions $options)
{
    // We will register a signal handler for the alarm signal so that we can kill this
    // process if it is running too long because it has frozen. This uses the async
    // signals supported in recent versions of PHP to accomplish it conveniently.
    pcntl_signal(SIGALRM, function () {
        $this->markJobAsFailedIfAlreadyExceedsMaxAttempts(
            $connectionName, $job, (int) $options->maxTries
        );

        $this->kill(1);
    });
```

**Comment by xyrintech** [comment]
You understanding is 100% correct. I can definitely try this code, one quick question. Which file / location will be the best place to try this function?

**Comment by djtarazona** [comment]
Well, Horizon is using the Laravel framework's queue for this logic, so you'd probably need to make this change above this line.

https://github.com/laravel/framework/blob/0fa42e3479341c99d9748e47be889fd8db99e034/src/Illuminate/Queue/Worker.php#L143

**Comment by xyrintech** [comment]
Hey,
By the way, I tried this thing you mentioned but no success. 
Any update how soon this bug will be resolved? :)
Thanks.

**Comment by themsaid** [comment]
Hey,

This isn't an issue with Horizon but laravel/framework.

I've addresses the issue here https://github.com/laravel/framework/pull/29024 and will close this issue since it's not related to Horizon.
