### ISSUE TITLE
Job is triggered even though deleted in Queue::before

### ISSUE THREAD

**Issue by lasselehtinen** [laravel/horizon#575]
- Horizon Version: 1.4.3
- Laravel Version: 5.6.39
- PHP Version: 7.2.9
- Redis Driver & Version: predis/phpredis v1.1.1
- Database Driver & Version: MySQL 5.7.23

### Description:
I am trying to build a logic to check if duplicate job already exists. The issue is that even running $job->delete() the job is still queued. I don't know the Laravel internals well enough, but is it because $job->fire() does not seem to check if the job has been already deleted? 

### Steps To Reproduce:

```php
Queue::before(function (JobProcessing $event) use ($jobs) {
    $event->job->delete();
});
```

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so feel free to reply and we'll try to have a look.

Thanks!

**Comment by lasselehtinen** [comment]
Thanks. I upgraded to Laravel 5.7 and Horizon to v3.1.1 and the same behavior happens. Could you reopen this issue?

**Comment by driesvints** [comment]
Sure, gonna check with @themsaid if he might know the answer to this.

**Comment by driesvints** [comment]
Heya, @lasselehtinen. The way the `before` method works is to ensure you have an active DB connection etc. The `delete` method for the job is only meant to be used within the job handling itself. If you need to check for duplicate jobs you'd best do this inside the handle method.

If we need to support the `delete` method in the `before` callback then that would be a new feature. This should be taken up by opening an issue on the laravel/ideas repo since it's related to the queue component and not so much Horizon.
