### ISSUE TITLE
Horizon is serving files through http on https website

### ISSUE THREAD

**Issue by darki73** [laravel/horizon#613]
**- Horizon Version:** 3.2.2
**- Laravel Version:** 5.8.22
**- PHP Version:** 7.3.5
**- Redis Driver & Version:** predis/phpredis 1.1.1
**- Database Driver & Version:** MariaDB 10.4

### Description:
![Annotation 2019-06-13 152853](https://user-images.githubusercontent.com/1318627/59432561-4a50fd80-8df0-11e9-8691-2818b6e0497d.png)
This is the reason i've created [this pull request](https://github.com/laravel/horizon/pull/570). Third installation, and still the same error.

Website is NOT local (well, it is local, however, it resolves to the real domain name), `APP_URL` starts with **https://**, yet it still tries to resolve the `css` and `js` files through **http://**.

### Steps To Reproduce:
Fresh installation on fresh Laravel installation

**Comment by driesvints** [comment]
I don't think this has anything to do with Horizon but rather the way your web server handles the requests. It's probably better if you ask this question on a support channel because you'll have a higher chance that someone could help you out to figure which thing is affecting your local setup.

If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
