### ISSUE TITLE
One job in the queue is not processed with 'minProcesses = 1'

### ISSUE THREAD

**Issue by rustik666** [laravel/horizon#895]
- Horizon Version: 4.3.5
- Laravel Version: 7.28.2
- PHP Version: 7.4.8
- Redis Driver & Version: predis/phpredis 5.3.1
- Database Driver & Version: MariaDB 10.4.12

### Description:
I'm experiencing and issue when Horizon is running but has `minProcesses` set to 0 and 1 job as pushed to the queue.

### Steps To Reproduce:

I put 1 job from Tinker to the queue and expected that this job will be handled. Nothing happened, I pushed 2 more jobs into the queue and Horizon started processing.

Please let me know if you need any additional details.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by rustik666** [comment]
Thanks a lot for such a fast answer!

**Comment by suhaboncukcu** [comment]
Hi @driesvints 
Sorry for taking your time, but I'm not sure I understand the support policy on this. The link you shared is laravel framework support policy and it says laravel7 will get security fixes till  "March 3rd, 2021" 

We planned for this change but can't upgrade the horizon to 5th version without laravel8 upgrade since it's indicated [here](https://github.com/laravel/horizon/blob/master/UPGRADE.md) that Laravel 8.0 is now the minimum required version.

So if this is a bug, we can't fix it till we upgrade framework to laravel8. Is that what you mean by the support policy? 

Thanks in advance.

**Comment by paras-malhotra** [comment]
This isn't a security fix. That's why the issue isn't supported. In fact, it's not even a bug. 

The OP was checking in Tinker and my guess is that because of the magic behind job dispatching (dispatched on `__destruct` of `PendingDispatch`), the destructor is called only on the next command (so the job actually is dispatched on the next command of Tinker). If you try this on a simple request, it will work.

**Comment by suhaboncukcu** [comment]
> This isn't a security fix. That's why the issue isn't supported. In fact, it's not even a bug.
> 
> The OP was checking in Tinker and my guess is that because of the magic behind job dispatching (dispatched on `__destruct` of `PendingDispatch`), the destructor is called only on the next command (so the job actually is dispatched on the next command of Tinker). If you try this on a simple request, it will work.

makes a lot of sense. Just wanted to understand if support policy is actually following a convention as:

horizon 4.x -> laravel 7.x
horizon 5.x -> laravel 8.x 

or not.

**Comment by driesvints** [comment]
@suhaboncukcu Horizon 4.x isn't supported anymore. Only 5.x. See:

> For all additional libraries, including Lumen, only the latest release receives bug fixes.

**Comment by robj** [comment]
@rustik666 - sorry the only version supported now is the one that is 17 days old, not the one widely used in production.

@rustik666 - I also experienced this issue in v5, and had my Issue closed immediately for not taking the problem to the outsourced Level 1 Help Desk.

@driesvints

**Comment by rustik666** [comment]
Got it, thank you @robj !

**Comment by driesvints** [comment]
@robj this isn't helping anyone. Like I said in the other issue, please be more considerate for project maintainers. You're using free software and you're acting pretty entitled here. [We have a support policy](https://laravel.com/docs/8.x/releases#support-policy) in place that clearly states that we only support the latest released major version of our first party packages.

I gave you a reply on the other issue where I tried out your bug but couldn't reproduce it and would appreciate it if you could first try some of the support channels before posting again.

**Comment by robj** [comment]
@driesvints cc @rustik666 - sorry @driesvints - I did get a chuckle , Its 2020 - (faux) outrage is quintessential!

Have a good weekend ❤️
